import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import Image from 'next/image'

const axios = require('axios');
axios.defaults.headers.common['Authorization'] = 'Bearer 2:Gwxyp4p98c8ek50z8WUGXSZdpnCjUd9VWjR6l3fqV3huIaewQ4cg';

const projectId = '21383131809';

export default function Home() {

  const [flagData, setFlagData] = useState([]);
  const [projectName, setProjectName] = useState('');
  const [featureData, setFeatureData] = useState([]);

  // Authenticate User :  https://app.optimizely.com/oauth2/authorize
  // https://library.optimizely.com/docs/api/app/v2/index.html#section/Authentication

  useEffect(() => {

    let environmentData = '';
    let featureData = '';

    // Get Project Data
    axios.get(`https://api.optimizely.com/v2/projects/${projectId}`)
    .then(function (response) {
      setProjectName(response.data.name)
    });

    axios.get(`https://api.optimizely.com/v2/environments?project_id=${projectId}`)
    .then(function (response) {
      environmentData = response.data.map(x => {
        return {
          name: x.name,
          datafile: JSON.stringify(x.datafile)
        };
      });
      setFlagData(environmentData);
    });

    axios.get(`https://api.optimizely.com/flags/v1/projects/${projectId}/flags`)
    .then(function (response) {
      featureData = response.data.items.map(x => {
        console.log('Flag Data', x);

        let data  = [];
        Object.keys(x.environments).forEach(function(key,index) {
          data.push({
              key: x.environments[key].key,
              enabled: x.environments[key].enabled,
              environment: x.environments[key].name
          });
        });

        return {
          key: x.key,
          data: data
        };
      });

      setFeatureData(featureData);
    })

  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Image src="/logo.png" alt="me" width="250" height="64" />

        <h1>
          Environments for {projectName}:
        </h1>

        <div>
          {flagData.map(({ name, datafile }, index) => (
            <div key={index}> {name} <br /> {datafile} </div>
          ))}
        </div>

        <h1>Features For Department</h1>

        <div>
            {featureData.map(({ key, data }, index) => (
            <>
            <h3>{key}</h3>
              {data.map(({ key, enabled, environment }, index) => (
                <p key={index}>
                  key={key} <br />
                  enabled={enabled} <br />
                  environment={environment} <br />
                  <button>Toggle flag with update_flags API</button>
                  {/* https://library.optimizely.com/docs/api/flags/v1/index.html#operation/update_flags */}
                </p>
              ))}

          </>)            )}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
